set expandtab
set hlsearch
set incsearch
set encoding=utf8

""" custom shortcuts
let mapleader = " "
nmap <silent> <leader>n :set nu! rnu!<CR>
nmap <silent> <leader>r :set rnu!<CR>
nmap <silent> <leader>s :w<CR>
nmap <silent> <leader>q :q<CR>
nnoremap <C-n><C-t> :NERDTreeToggle<CR>
nnoremap <C-n><C-f> :NERDTreeFind<CR>

""" autocmds
autocmd Filetype markdown setlocal complete+=kspell textwidth=120 " Automatic wrapping
autocmd Filetype gitcommit setlocal complete+=kspell textwidth=72 " Automatic git commit wrapping

""" plugins
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'preservim/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'instant-markdown/vim-instant-markdown', {'for': 'markdown'}
Plug 'ryanoasis/vim-devicons'
Plug 'bryanmylee/vim-colorscheme-icons'
Plug 'christophermca/meta5'
call plug#end()
" markdown preview
let g:instant_markdown_autostart = 0
let vim_markdown_preview_github=1
" nerdtree
" Exit Vim if NERDTree is the only window left.
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() |
  \ quit | endif

""" syntax highlighting
syntax on
colo meta5
" clear bg
hi Normal      ctermbg=NONE guibg=NONE
hi EndOfBuffer ctermbg=NONE guibg=NONE
" better diff
hi diffAdded   ctermbg=NONE ctermfg=46  cterm=NONE guibg=NONE guifg=#00FF00 gui=NONE
hi diffRemoved ctermbg=NONE ctermfg=196 cterm=NONE guibg=NONE guifg=#FF0000 gui=NONE
hi link diffLine String
hi link diffSubname Normal
